<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
    <div class="right_col" role="main">
      <div class="">
        <!-- 用户名单 start -->
        <div class="row x_title">
          <div class="col-md-6">
            <h3>用户名单</h3>
          </div>
        </div>
        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-9">
                  <form class="search-form">
                    <div class="col-sm-2" style="padding-left: 0px">
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="请输入用户ID" value="<?php echo $this->username;?>" name="username">
                      </label>
                    </div>
                    <div class="col-sm-2" style="padding-left: 0px">
                    <label>
                      <input type="text" class="form-control input-sm" placeholder="请输入公司名称"  value="<?php echo $this->name;?>" name="name">
                    </label>
                  </div>
                  <button class="btn btn-primary btn-sm">搜索</button>
                  </form>
                  <a class="btn btn-default btn-sm" id="open" style="margin-top: 5px;">开户</a>
                </div>
                <div class="col-sm-3">
                  <div class="dataTables_filter">
                    <label>
                      <select class="form-control input-sm" id="selectPage">
                        <option value="15" <?php echo $pagelimit == 15? 'selected':''?>>15</option>
                        <option value="20" <?php echo $pagelimit == 20? 'selected':''?>>20</option>
                        <option value="50" <?php echo $pagelimit == 50? 'selected':''?>>50</option>
                        <option value="100" <?php echo $pagelimit == 100? 'selected':''?>>100</option>
                      </select>
                    </label>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>用户ID</th>
                        <th>公司名称</th>
                        <th>短信类型</th>
                        <th>短信余额</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <?php if(!empty($this->pager->getList())):?>
                      <?php foreach ($this->pager->getList() as $key=>$value):?>
                        <tbody>
                        <tr>
                            <td><?php echo $value['username'];?></td>
                            <td><?php echo $value['name'];?></td>
                            <td><?php echo $this->accounts[$value['type']]?></td>
                            <td><?php echo $value['type']==1?$value['show_normal_balance']:$value['show_marketing_balance'];?></td>
                            <td>
                                <a class="btn btn-default btn-sm recharge" data-id="<?php echo $value['id'];?>">充值</a>
                                <a class="btn btn-default btn-sm rollback" data-id="<?php echo $value['id'];?>">回退</a>
                                <a class="btn btn-default btn-sm reset" data-id="<?php echo $value['id'];?>">重置密码</a>
                                <a class="btn btn-default btn-sm delete" data-id="<?php echo $value['id'];?>">帐号删除</a>
                                <a class="btn btn-default btn-sm setCallbackUrl" data-id="<?php echo $value['id'];?>">设置回调地址</a>
                            </td>
                        </tr>
                        </tbody>
                      <?php endforeach;?>
                    <?php else:?>
                      <tbody>
                      <tr><td colspan="16">没有找到用户</td></tr>
                      </tbody>
                    <?php endif;?>
                  </table>
                  <?php echo $this->renderTpl('public/pagination.phtml',array(),'index');?>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- 用户名单 end -->

        <div class="modal fade bs-example-modal-sm" id="rechargeModal">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">充值</h4>
              </div>
                <span>类型</span>
                <label>
                    <select class="form-control input-sm" name="raccount" id="raccount">
                        <option value="1">行业短信</option>
                        <option value="2">营销短信</option>
                    </select>
                </label>
              <div class="modal-body">
                <input type="text" name="recharge" class="form-control input-sm" placeholder="请输入充值数目">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="recharge">充值</button>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade bs-example-modal-sm" id="rollbackModal">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">回退</h4>
              </div>
                <span>类型</span>
                <label>
                    <select class="form-control input-sm" name="baccount" id="baccount">
                        <option value="1">行业短信</option>
                        <option value="2">营销短信</option>
                    </select>
                </label>
              <div class="modal-body">
                <input type="text" name="rollback" class="form-control input-sm" placeholder="请输入回退数目">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="rollback">回退</button>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade bs-example-modal-sm" id="resetModal">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">重置密码</h4>
              </div>
              <div class="modal-body">
                <input type="text" name="reset" class="form-control input-sm" placeholder="请输入新密码">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="reset">重置密码</button>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade bs-example-modal-sm" id="deleteModal">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="delTitle">身份确认</h4>
              </div>
              <div class="modal-body">
                <input type="password" name="surePwd" class="form-control input-sm" placeholder="请输入密码">
                <div class="none" id="wrapper">
                  <p id="arriText">初始删除率: <span id="arrivalRate"></span></p>
                  <input type="text" name="rate" class="form-control input-sm" placeholder="请输入删除率" id="rate">
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="deletePrev">下一步</button>
                <button type="button" class="btn btn-primary none" id="deleteSure">确定</button>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade bs-example-modal-md" id="openModal">
          <div class="modal-dialog modal-md">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">用户开户</h4>
              </div>
              <div class="modal-body open-user-modal">
                <form class="form-horizontal form-label-left" id="userForm">
                  <div class="form-group">
                    <label class="control-label col-sm-3">短信类型</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <div class="radio col-md-3">
                        <label><input type="radio" name="type" value="1" checked>行业短信</label>
                      </div>
                      <div class="radio col-md-3">
                        <label><input type="radio" name="type" value="2">营销短息</label>
                      </div>
                      <div class="radio col-md-3">
                        <label><input type="radio" name="type" value="3">特殊短信</label>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-sm-3">帐号</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input name="username" type="text" class="form-control" placeholder="请输入帐号">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-sm-3">密码</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input name="password" type="text" class="form-control" placeholder="请输入密码">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-sm-3">公司名称</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input name="companyName" type="text" class="form-control" placeholder="请输入公司名称">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-sm-3">接口账户</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input name="account" type="text" class="form-control" placeholder="请输入接口账户">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-sm-3">接口密码</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input name="rawPassword" type="text" class="form-control" placeholder="请输入接口密码">
                    </div>
                  </div>
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="openBtn">开户</button>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade bs-example-modal-sm" id="urlModal">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">设置回退地址</h4>
              </div>
              <div class="modal-body">
                <input type="text" name="collbackUrl" class="form-control input-sm" placeholder="请输入回退地址">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="setUrl">确定</button>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
<script src="/script/user/index.js"></script>
<?php $this->display("public/footer.phtml"); ?>