<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-6">
            <h3>用户名单</h3>
          </div>
        </div>
        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-9">
                  <form class="search-form">
                    <span>用户</span>
                    <label>
                      <select class="form-control input-sm" name="users">
                          <option value="0">全部</option>
                          <?php foreach ($this->users as $key =>$value):?>
                              <option value="<?php echo $key;?>" <?php echo $key==$this->userid?'selected':'';?>><?php echo $value;?></option>
                          <?php endforeach;?>
                      </select>
                    </label>
                    <span>账户类型</span>
                    <label>
                      <select class="form-control input-sm" name="account">
                          <option value="0">全部</option>
                        <?php foreach ($this->accounts as $key =>$value):?>
                            <option value="<?php echo $key;?>" <?php echo $key==$this->account?'selected':'';?>><?php echo $value;?></option>
                        <?php endforeach;?>
                      </select>
                    </label>
                    <span>操作类型</span>
                    <label>
                      <select class="form-control input-sm" name="actions">
                          <option value="0">全部</option>
                          <?php foreach ($this->actions as $key =>$value):?>
                              <option value="<?php echo $key;?>" <?php echo $key==$this->direction?'selected':'';?>><?php echo $value;?></option>
                          <?php endforeach;?>
                      </select>
                    </label>
                    <div class="input-prepend input-group">
                      <span class="add-on input-group-addon"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i></span>
                      <input type="text" style="width: 200px" name="time" id="reservation" class="form-control">
                    </div>
                    <button class="btn btn-primary btn-sm">搜索</button>
                  </form>
                </div>
                <div class="col-sm-3">
                  <div class="dataTables_filter">
                    <label>
                      <select class="form-control input-sm" id="selectPage">
                        <option value="15" <?php echo $pagelimit == 15? 'selected':''?>>15</option>
                        <option value="20" <?php echo $pagelimit == 20? 'selected':''?>>20</option>
                        <option value="50" <?php echo $pagelimit == 50? 'selected':''?>>50</option>
                        <option value="100" <?php echo $pagelimit == 100? 'selected':''?>>100</option>
                      </select>
                    </label>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>用户ID</th>
                        <th>账户类型</th>
                        <th>操作类型</th>
                        <th>数量</th>
                        <th>时间</th>
                      </tr>
                    </thead>
                  <?php if(!empty($this->pager->getList())):?>
                    <?php $mapper = \Mapper\UsersModel::getInstance();?>
                    <?php foreach ($this->pager->getList() as $key=>$value):?>
                    <tbody>
                      <tr>
                        <td><?php echo $mapper->getUsername($value['user_id']);?></td>
                        <td><?php echo $this->accounts[$value['type']]?></td>
                        <td><?php echo $this->actions[$value['direction']]?></td>
                        <td><?php echo $value['show_amount'];?></td>
                        <td><?php echo $value['created_at'];?></td>
                      </tr>
                    </tbody>
                    <?php endforeach;?>
                    <?php else:?>
                    <tbody>
                      <tr><td colspan="16">没有找到记录</td></tr>
                    </tbody>
                  <?php endif;?>
                  </table>
                  <?php echo $this->renderTpl('public/pagination.phtml',array(),'index');?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
<?php $this->display("public/footer.phtml"); ?>