        <!-- 头部nav start -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="images/img.jpg" alt=""><?php echo $adminUser->getUsername();?>
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;" id="pwdModalBtn">修改密码</a></li>
                    <li><a href="/logout">退出</a></li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- 头部nav end -->

        <div class="modal fade bs-example-modal-sm" id="pwdModal">
          <div class="modal-dialog modal-md">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">修改密码</h4>
              </div>
              <div class="modal-body">
                <form class="form-horizontal form-label-left" id="editPwdForm">
                  <div class="form-group">
                    <label class="control-label col-sm-3">原密码</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input name="old" type="password" class="form-control" placeholder="请输入原密码">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-sm-3">新密码</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input name="new" type="password" class="form-control" placeholder="请输入新密码">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-sm-3">确认新密码</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input name="sure" type="password" class="form-control" placeholder="请确认新密码">
                    </div>
                  </div>
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="exitPwdBtn">修改密码</button>
              </div>
            </div>
          </div>
        </div>

        <div style="clear: both;overflow: hidden;"></div>