<style type="text/css">
.pagination-li .pagination-span-front{
  display: inline-block;
  border: 1px solid #ebebeb;
  border-right: 0px;
  height: 29px;
  width: 45px;
  vertical-align: middle;
  text-align: center;
  line-height: 29px;
  color: #919191;
  background-color: #f3f3f3;
  margin-left: 10px;
}
.pagination-li input.pagination-input{
  display: inline-block;
  line-height: 1.4;
  border:1px solid #ebebeb;
  background-color: #fff;
  height: 29px;
  width: 40px;
}
.pull-right .pagination-sm .i-height i:before{

}
 .checkbox input.pagination-input{
  display: inline-block;
  line-height: 1.4;
  border:1px solid #ebebeb;
  background-color: #fff;
  height: 26px;
  width: 30px;
 }
 .form-group label.label-font-size{
  font-size: 14px;
 }
.pagination-li .pagination-span-back{
  display: inline-block;
  border: 1px solid #ebebeb;
  border-left: 0px;
  height: 29px;
  width: 35px;
  vertical-align: middle;
  text-align: center;
  line-height: 29px;
  color: #919191;
  background-color: #f3f3f3;
}
.pagination-li a#pagination-a{
  float: right;
}
.pagination-wrapper .dataTables_paginate a {
  background-color: #fff !important;
}
.pagination-wrapper .pagination>.active>a {
  color: #fff;
  background-color: #337ab7 !important;
}
</style>
<?php if($this->pager->getPageCount()>1):?>
  <?php $pageUrl = $this->uri(array());?>
  <div class="row">
    <div class="col-xs-6 col-left" >
      <div class="dataTables_info">总<?php echo $this->pager->getItemTotal();?>条数据，共<?php echo $this->pager->getPageCount();?>页</div>
    </div>
    <div class="col-xs-6 col-right pagination-wrapper">
      <div class="dataTables_paginate paging_bootstrap pull-right">
        <ul class="pagination pagination-sm" style="margin: 0px; padding: 0px;">
          <?php if($this->pager->getPage()>1):?>
          <li class="fa-hover">
            <a href="<?php echo $this->uri(array('page'=>$this->pager->getPage()-1));?>" aria-label="Previous">
              <i class="fa fa-chevron-left"></i>
            </a>
          </li>
          <?php endif;?>
          <?php foreach ($this->pager->getRangList() as $key => $num):?>
            <?php if($num == $this->pager->getPage()):?>
            <li class="active"><a href="#"><?php echo $num;?></a></li>
            <?php else: ?>
            <li><a href="<?php echo $this->uri(array('page'=>$num));?>"><?php echo $num;?></a></li>
            <?php endif;?>
          <?php endforeach;?>
          <?php if($this->pager->getPage()<$this->pager->getPageCount()):?>
            <li class="fa-hover">
              <a href="<?php echo $this->uri(array('page'=>$this->pager->getPage()+1));?>" aria-label="Next" class="i-height">
                <i class="fa fa-chevron-right"></i>
              </a>
            </li>
          <?php endif;?>
          <li class="pagination-li">
            <sapn class="pagination-span-front">转到第</sapn><input class="pagination-input" name="inputPage" id="inputPage"><sapn class="pagination-span-back">页</sapn>
            <a href="" data-url="<?php echo $pageUrl;?>" class="btn btn-default pageButton" id="pagination-a">确定</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <?php else:?>
  <div class="row">
    <div class="col-xs-6 col-left">
      <div class="dataTables_info">总<?php echo $this->pager->getItemTotal();?>条数据，共<?php echo $this->pager->getPageCount();?>页
          
      </div>
    </div>
  </div>
<?php endif;?>

<script type="text/javascript">
  /* 跳转页数 start */
  (function(){
    $(".pageButton").click(function () {
      var inputPage = $("#inputPage").val();
      if(inputPage == ''){
        inputPage = 1;
      }
      var url = $(this).attr('data-url')+'&page='+inputPage;
      $(this).attr('href',url);
    });
  })();
  /* 跳转页数 end */
</script>


