<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
      <div class="right_col" role="main">
        <div class="">
          <!-- 用户名单 start -->
          <div class="row x_title">
            <div class="col-md-6">
              <h3>处理进度</h3>
            </div>
          </div>
          <div class="x_content">
            <div class="text-muted font-13 m-b-30">
              <div class="dataTables_wrapper dt-bootstrap no-footer">
                <div class="row">
                  <div class="col-sm-9">
                    <form class="search-form">
                      <span>子账户</span>
                      <label>
                        <select class="form-control input-sm" name="userid">
                            <option value="0" <?php echo 0==$this->userid?'selected':'';?>>全部</option>
                            <?php foreach ($this->users as $key =>$value):?>
                                <option value="<?php echo $key;?>" <?php echo $key==$this->userid?'selected':'';?>><?php echo $value;?></option>
                            <?php endforeach;?>
                        </select>
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="公司名称" value="<?php echo $this->company;?>" name="company">
                      </label>
                      <span>短信类型</span>
                      <label>
                        <select class="form-control input-sm" name="type">
                            <option value="0" <?php echo 0==$this->type?'selected':'';?>>全部</option>
                            <?php foreach ($this->sendTypes as $key =>$value):?>
                                <option value="<?php echo $key;?>" <?php echo $key==$this->type?'selected':'';?>><?php echo $value;?></option>
                            <?php endforeach;?>
                        </select>
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="短信签名" value="<?php echo $this->sign;?>" name="sign">
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="短信内容" value="<?php echo $this->content;?>" name="content">
                      </label>
                      <div class="input-prepend input-group">
                        <span class="add-on input-group-addon"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i></span>
                        <input type="text" style="width: 200px" name="time" id="reservation" class="form-control" value="">
                      </div>
                      <button class="btn btn-primary btn-sm" type="submit">搜索</button>
                    </form>
                  </div>
                  <div class="col-sm-3">
                    <div class="dataTables_filter">
                      <label>
                        <select class="form-control input-sm" id="selectPage">
                          <option value="15" <?php echo $pagelimit == 15? 'selected':''?>>15</option>
                          <option value="20" <?php echo $pagelimit == 20? 'selected':''?>>20</option>
                          <option value="50" <?php echo $pagelimit == 50? 'selected':''?>>50</option>
                          <option value="100" <?php echo $pagelimit == 100? 'selected':''?>>100</option>
                        </select>
                      </label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>用户ID</th>
                          <th>公司名称</th>
                          <th>号码归属地</th>
                          <th>号码数量</th>
                          <th>总提交数</th>
                          <th>计费数</th>
                          <th>创建时间</th>
                          <th>短信类型</th>
                          <th>短信签名</th>
                          <th>短信内容</th>
                          <th>任务进度</th>
                        </tr>
                      </thead>

                    <?php if(!empty($this->pager->getList())):?>
                      <?php $mapper = \Mapper\UsersModel::getInstance();?>
                      <?php foreach ($this->pager->getList() as $key=>$value):?>
                      <tbody>
                        <tr>
                          <td><?php echo $mapper->getUsername($value['user_id']);?></td>
                          <td><?php echo $mapper->getName($value['user_id']);?></td>
                          <td><?php echo $value['area'];?></td>
                          <td><?php echo $value['quantity'];?></td>
                          <td><?php echo $value['billing_amount'];?></td>
                          <td><?php echo $value['billing_count'];?></td>
                          <td><?php echo $value['created_at'];?></td>
                          <td><?php echo $this->sendTypes[$value['sms_type']];?></td>
                          <td><?php echo $value['sign'];?></td>
                          <td><?php echo $value['content'];?></td>
                          <td><?php echo $this->status[$value['status']];?></td>
                        </tr>
                      </tbody>
                      <?php endforeach;?>
                    <?php else:?>
                    <tbody>
                      <tr><td colspan="16">没有找到记录</td></tr>
                    </tbody>
                    <?php endif;?>
                    </table>
                    <?php echo $this->renderTpl('public/pagination.phtml',array(),'index');?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<?php $this->display("public/footer.phtml"); ?>