<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-6">
            <h3>待处理任务</h3>
          </div>
        </div>
        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-9">
                  <form class="search-form">
                    <div class="col-sm-2" style="padding-left: 0">
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="请输入用户ID" value="<?php echo $this->username;?>" name="username">
                      </label>
                    </div>
                    <div class="col-sm-2" style="padding-left: 0">
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="请输入公司名称" value="<?php echo $this->company;?>" name="company">
                      </label>
                    </div>
                    <button class="btn btn-primary btn-sm">搜索</button>
                  </form>
                </div>
                <div class="col-sm-3">
                  <div class="dataTables_filter">
                    <label>
                      <select class="form-control input-sm" id="selectPage">
                        <option value="15" <?php echo $pagelimit == 15? 'selected':''?>>15</option>
                          <option value="20" <?php echo $pagelimit == 20? 'selected':''?>>20</option>
                          <option value="50" <?php echo $pagelimit == 50? 'selected':''?>>50</option>
                          <option value="100" <?php echo $pagelimit == 100? 'selected':''?>>100</option>
                      </select>
                    </label>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>用户ID</th>
                        <th>公司名称</th>
                        <th>号码归属地</th>
                        <th>号码数量</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                  <?php if(!empty($this->pager->getList())):?>
                    <?php $mapper = \Mapper\UsersModel::getInstance();?>
                    <?php foreach ($this->pager->getList() as $key=>$value):?>
                    <tbody>
                      <tr>
                        <td><?php echo $mapper->getUsername($value['user_id']);?></td>
                        <td><?php echo $mapper->getName($value['user_id']);?></td>
                        <td><?php echo $value['area'];?></td>
                        <td><?php echo $value['quantity'];?></td>
                        <td>
                          <a class="btn btn-default btn-sm recharge" href="/index/job/send?id=<?php echo $value['id'];?>">发送</a>
                          <a class="btn btn-default btn-sm rollback" data-id="<?php echo $value['id'];?>">驳回</a>
                        </td>
                      </tr>
                    </tbody>
                    <?php endforeach;?>
                  <?php else:?>
                    <tbody>
                      <tr><td colspan="16">没有找到记录</td></tr>
                    </tbody>
                  <?php endif;?>
                  </table>
                  <?php echo $this->renderTpl('public/pagination.phtml',array(),'index');?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade bs-example-modal-md" id="rejectModal">
      <div class="modal-dialog modal-md" style="margin: 0;position: absolute;top: 40%;left: 50%;transform: translate(-40%,-50%);width: 400px;">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">驳回</h4>
          </div>
          <div class="modal-body">
            是否驳回该任务？
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            <button type="button" class="btn btn-primary" id="sure">确定</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="/script/job/index.js"></script>
<?php $this->display("public/footer.phtml"); ?>